
pipeline {
    agent any
    tools {
        maven 'maven3'
    }
    stages {
        stage ('Checkout') {
            steps {
                git 'https://github.com/sk12k/addressbook.git'
            }
        }
    }
}



